// ════════════════════════════════════════════════════════════════
// BetterUs Brand System™ — single source of truth for proprietary naming.
// Positioning: "The Relationship Operating System for Modern Couples."
// BetterUs is a Relationship Intelligence Platform — never a "chatbot" or "quiz".
// ════════════════════════════════════════════════════════════════

export const BRAND = {
  product: "BetterUs",
  positioning: "The Relationship Operating System for Modern Couples",
  category: "AI-Powered Relationship Intelligence Platform",

  engine: "BetterUs Relationship Intelligence Engine™",
  engineShort: "Relationship Intelligence Engine™",
  engineVersion: "v1.0",
  poweredBy: "Powered by the BetterUs Relationship Intelligence Engine™",

  reportTitle: "BetterUs Relationship Intelligence Report™",
  generatedBy: "Generated by the BetterUs Relationship Intelligence Engine™",
  coach: "BetterUs Coach™",
} as const;

// The proprietary engine suite — names + taglines used for badges/sections.
export const ENGINES = {
  intelligence: {
    name: "Relationship Intelligence Engine™",
    tagline: "Analyzes relationship health beyond surface-level scores.",
  },
  health: {
    name: "Relationship Health™",
    tagline: "Your weighted, multi-dimensional health score.",
  },
  trust: {
    name: "Trust Risk Engine™",
    tagline: "Detect hidden trust fractures before they become relationship crises.",
  },
  communication: {
    name: "Communication Breakdown Engine™",
    tagline: "Identify the patterns silently damaging connection.",
  },
  stage: {
    name: "Relationship Stage Engine™",
    tagline: "Understand exactly where your relationship stands today.",
  },
  recovery: {
    name: "Recovery Potential Engine™",
    tagline: "Predict how likely your relationship is to recover and improve.",
  },
  dna: {
    name: "Relationship DNA Engine™",
    tagline: "Reveal how you love, connect, communicate, and repair.",
  },
  sync: {
    name: "Couple Sync Engine™",
    tagline: "Measure how differently each partner experiences the same relationship.",
  },
  drift: {
    name: "Emotional Drift Engine™",
    tagline: "Track relationship momentum over time.",
  },
} as const;

// Recovery plans → branded "Blueprints".
export const BLUEPRINT = {
  section: "Personalized Recovery Blueprint™",
  generatedBy: BRAND.generatedBy,
  byHorizon: {
    7: "7-Day Reset Blueprint™",
    30: "30-Day Reconnection Blueprint™",
    90: "90-Day Relationship Recovery Blueprint™",
  } as Record<number, string>,
};
